---
- hosts: routers
  connection: network_cli
  vars:
    valid_dns: "{{ extra_dns | ipaddr }}"

  tasks:
  - debug:
      var: valid_dns

  - name: Set default DNS
    net_system:
      name_servers:
        - 8.8.8.8
        - 8.8.4.4

    register: commands

  - assert:
      that:
        -  "valid_dns != false"
      msg: "Not valid DNS IP!"
    when: extra_dns is defined

  - name: Set extra DNS
    net_system:
      name_servers:
        - "{{ extra_dns }}"
    register: commands
    when: extra_dns is defined and valid_dns != False
